version: '3.9'

services:
  db:
    image: postgres:11
    container_name: spring-postgres
    hostname: spring-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  db:
    driver: local
